### ISSUE TITLE
Fabric mod?

### ISSUE THREAD

**Issue by Entropy159** [Matistan/MinecraftSharedInventory#1]
This is the only thing of it's kind I could find. I need a fabric mod that does this. Is that possible for you?

**Comment by Entropy159** [comment]
If you're not up for making the mod, I could probably do it if I got an explanation of how you did it in the plugin.

**Comment by Matistan** [comment]
Hi!
I was only making spigot plugins in the past, but can try to figure out how to make it compatible for fabric. Just give me a few days.

**Comment by Matistan** [comment]
Please contact me on Discord if you're still interested in this mod. My username there is the same as it is on GitHub - Matistan. Looking forward to connecting with you!

**Comment by Entropy159** [comment]
I am still interested, but I don't have discord.

**Comment by Matistan** [comment]
Ok, so please contact me through email (in my bio) to discuss details.
